name: Java CI with Maven

on: [ push ]

jobs:
  build:
    strategy:
      matrix: 
        jdk: [22, 23, 24]

    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
      - uses: actions/checkout@v3
      - name: 'Set up latest JDK ${{ matrix.jdk }} from jdk.java.net'
        uses: oracle-actions/setup-java@v1
        with:
          website: jdk.java.net
          release: ${{ matrix.jdk }}
      - name: Build with Maven
        run: mvn -B package --file pom.xml
